### PR TITLE
Improve security of provider tenant creation

### PR DESCRIPTION
**Pull request by cdosborn**
There were several legacy issues. This simplifies the hashpass method to 13
lines which are easy to verify for correctness. Support was removed for
salting, as there was not a strong usecase. Shared providers cannot
individually salt, since each needs access. A non-shared provider could salt.

Here is the `hashpass` method that was  [changed](https://github.com/cdosborn/atmosphere/blob/3a4b16fbba3f16a3aac8b04f2a7002f2127fe9d4/service/accounts/openstack_manager.py#L581-L594).

### CODE REVIEW

**Comment by steve-gregory** [comment]
:shipit: Thanks @cdosborn

**Comment by lenards** [comment]
Nice work Connor.

**Comment by cdosborn** [comment]
🍦 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🐫

**Comment by cdosborn** [comment]
🍦 &nbsp;&nbsp;&nbsp;🐫

**Comment by cdosborn** [comment]
🍦 &nbsp;&nbsp;&nbsp;🐫

**Comment by cdosborn** [comment]
🍦&nbsp;&nbsp;🐫

**Comment by cdosborn** [comment]
🍦&nbsp;🐫

**Comment by cdosborn** [comment]
🍦🐫

**Comment by cdosborn** [comment]
🐫  💯

**Pull request merged**
